export {default as Header} from './Header';
export {default as MainBanner} from './MainBanner';
export {default as Highlights} from './Highlights';
export {default as Brands} from './Brands';
export {default as GoalsCollections} from './GoalsCollections';
export {default as Trending} from './Trending';
export {default as Footer} from './Footer';
export {default as SupplementsOverview} from './SupplementsOverview';
export {default as Cart} from './Cart';
